Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/nbclient/client.py", line 664, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from compiam.melody import Melodia
melodia = Melodia()  # initializing a melodia instance
pitch_track = melodia.extract("/path/to/audio")

------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
[0;32m/tmp/ipykernel_2989/142289344.py[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;32mfrom[0m [0mcompiam[0m[0;34m.[0m[0mmelody[0m [0;32mimport[0m [0mMelodia[0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0mmelodia[0m [0;34m=[0m [0mMelodia[0m[0;34m([0m[0;34m)[0m  [0;31m# initializing a melodia instance[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 3[0;31m [0mpitch_track[0m [0;34m=[0m [0mmelodia[0m[0;34m.[0m[0mextract[0m[0;34m([0m[0;34m"/path/to/audio"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/compiam/melody/melodia.py[0m in [0;36mextract[0;34m(self, path_to_audio)[0m
[1;32m     75[0m         """
[1;32m     76[0m         [0;32mif[0m [0;32mnot[0m [0mos[0m[0;34m.[0m[0mpath[0m[0;34m.[0m[0mexists[0m[0;34m([0m[0mpath_to_audio[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 77[0;31m             [0;32mraise[0m [0mValueError[0m[0;34m([0m[0;34m"Target audio not found."[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     78[0m         [0maudio[0m [0;34m=[0m [0mestd[0m[0;34m.[0m[0mEqloudLoader[0m[0;34m([0m[0mfilename[0m[0;34m=[0m[0mpath_to_audio[0m[0;34m)[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     79[0m         extractor = estd.PredominantPitchMelodia(

[0;31mValueError[0m: Target audio not found.
ValueError: Target audio not found.

